<?php

namespace Lpi\NewsBundle\Block;


use Lpi\NewsBundle\Repository\NewsRepository;
use Sonata\BlockBundle\Block\BaseBlockService;
use Sonata\BlockBundle\Block\BlockContextInterface;
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class SliderService extends BaseBlockService
{
    /**
     * @var NewsRepository
     */
    private $repository;

    public function __construct($name, EngineInterface $templating, NewsRepository $repository)
    {
        parent::__construct($name, $templating); // TODO: Change the autogenerated stub

        $this->repository = $repository;
    }


    public function setDefaultSettings(OptionsResolverInterface $resolver)
    {
        parent::setDefaultSettings($resolver); // TODO: Change the autogenerated stub
        $resolver->setOptional(['slider']);
    }

    public function execute(BlockContextInterface $blockContext, Response $response = null)
    {
        return $this->renderResponse('LpiNewsBundle:Block:slider.html.twig', array(

            'block' => $blockContext->getBlock(),
            'news' => $this->repository->listArticleForSlider($blockContext->getSetting('slider'))

        ), $response);
    }

}